### **Python Assignment: Data Structures, Functions, Numpy & Pandas**

# Section A: Data Structures & Control Structures



1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
sample = [3,5,8,6,7]
sample.append(11)
print("List after appending : ", sample)
sample.extend([12,17])
print("List after extending : ", sample)
sample.insert(1,4)
print("List after inserting : ", sample)
sample.remove(3)
print("List after removing : ", sample)
sample.pop(len(sample)-1)
print("List after popping : ", sample)
print("Index of 12 : ", sample.index(12))
print("Count of 4 : ", sample.count(4))
sample.sort()
print("List after sorting : ", sample)
sample.reverse()
print("List after reversing : ", sample)
sample.clear()
print("List after clearing : ", sample)

List after appending :  [3, 5, 8, 6, 7, 11]
List after extending :  [3, 5, 8, 6, 7, 11, 12, 17]
List after inserting :  [3, 4, 5, 8, 6, 7, 11, 12, 17]
List after removing :  [4, 5, 8, 6, 7, 11, 12, 17]
List after popping :  [4, 5, 8, 6, 7, 11, 12]
Index of 12 :  6
Count of 4 :  1
List after sorting :  [4, 5, 6, 7, 8, 11, 12]
List after reversing :  [12, 11, 8, 7, 6, 5, 4]
List after clearing :  []

2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [4]:
# 1. Create a tuple storing 3 student names
students = ("Jyoti", "Rahul", "vivek")
print(f"Original tuple: {students}")

# 2. Try changing the second name (index 1)
try:
    students[1] = "David"
except TypeError as e:
    print(f"\nWhat happens? An error occurs!")
    print(f"Error Message: {e}")

Original tuple: ('Jyoti', 'Rahul', 'vivek')

What happens? An error occurs!
Error Message: 'tuple' object does not support item assignment

3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [7]:
# Create a set of integers with some duplicate values
my_set = {1, 2, 2, 3, 4, 4, 5}
print(my_set) # when print the set autometically remove the duplicate values

{1, 2, 3, 4, 5}

4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [8]:
# Create a dictionary with the keys:
person = {
    'name': 'jyoti',
    'age': 28,
    'city': 'cuttack'
}
print(f"Original dictionary: {person}")

# Update the age
person['age'] = 29

# Add a new key 'email'
person['email'] = 'jyotiranjansahoo1432@gmail.com'

#Print the final dictionary
print(f"Final dictionary   : {person}")

Original dictionary: {'name': 'jyoti', 'age': 28, 'city': 'cuttack'}
Final dictionary   : {'name': 'jyoti', 'age': 29, 'city': 'cuttack', 'email': 'jyotiranjansahoo1432@gmail.com'}

5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message

In [11]:
age = 20
if age >= 18:  #check the eligibility condition
  print(f"Age: {age} -> You are Eligible to Vote")
else:
  print(f"Age: {age} -> You are Not Eligible for Votr")

Age: 20 -> You are Eligible to Vote

6.Given a 'marks' variable, print the grade:

*   90 and above: 'A'

*   75–89: 'B'
*   50–74: 'C'
*   Below 50: 'Fail'

In [20]:

  marks= int(input("enter your marks\n"))
  if marks >=90:
        grade = 'A'
  elif (marks>= 75) and (marks<=89):
        grade = 'B'
  elif (marks>= 50) and (marks<=74):
        grade = 'c'
  else:
    grade = 'Fail'
  print(f"Marks: {marks} -> Grade: {grade}")

enter your marks
20
Marks: 20 -> Grade: Fail

7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [30]:
number = int(input("enter number"))
if number>=0 and number%2==0:
        print("is positive and even")
elif number>=0 and number%2 !=0:
        print("is positive and odd")
elif number<0 and number%2 ==0:
        print("is Negative and even")
elif number<0 and number%2 !=0:
        print("is Negative and odd")
elif number==0:
        print("is zero")

enter number12
is positive and even

# Section B: Numpy
8.Create:

* A scalar using np.array(5)
* A 1D array with values 1 to 5
* A 2D array (2x3) with values from 10 to 60 in steps of 10

In [31]:
import numpy as np

In [34]:
scalar = np.array(5)
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[10, 20, 30],[40, 50, 60]])
print(scalar,arr_1d,arr_2d,sep="\n")

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]

9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [35]:
random = np.random.randint(0, 100, size=(4, 4))
print(random)

[[54 32 92 52]
 [64 68 52 55]
 [ 1  9 13 53]
 [21 91 44 41]]

10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [36]:
import pandas as pd

In [39]:
array_2D = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
df = pd.DataFrame(array_2D, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

# Section C: Exploring Pandas
10.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
* Use .info(), .describe()
* Select 'Name' and 'City' columns
* Drop 'City' column
* Fill any missing values in 'Salary' column with the mean
* Remove any duplicate rows

In [47]:
data = {
    'Name': ['Ajay', 'Bijay', 'Chandan', 'Debasish', 'Elina', 'Fapul', 'Ganesh', 'Hari', 'Itu', 'Jyoti'],
    'Age': [25, 30, 20, 50, 35, 47, 55, 53, 60, 79],
    'City': ['cuttack', 'bhubaneswar', 'baripad', 'kandarpur', 'khurds', 'jajpur', 'banglore', 'mumbai', 'puri', 'Bihar'],
    'Salary': [23000, 24000, 80000, None, 50000, 20000, 120000, 100000, 140000, 150000]
}
df = pd.DataFrame(data)

In [42]:
print("info" , df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
info None

In [43]:
print("Describe",df.describe())

Describe              Age         Salary
count  10.000000      10.000000
mean   45.400000  100700.000000
std    18.019742   85309.957736
min    20.000000   20000.000000
25%    31.250000   30500.000000
50%    48.500000   90000.000000
75%    54.500000  135000.000000
max    79.000000  300000.000000

In [46]:
print(df[['Name', 'City']])

       Name         City
0      Ajay      cuttack
1     Bijay  bhubaneswar
2   Chandan      baripad
3  Debasish    kandarpur
4     Elina       khurds
5     Fapul       jajpur
6    Ganesh     banglore
7      Hari       mumbai
8       Itu         puri
9     Jyoti        Bihar

In [48]:
df.drop('City', axis=1, inplace=True)
df

       Name  Age    Salary
0      Ajay   25   23000.0
1     Bijay   30   24000.0
2   Chandan   20   80000.0
3  Debasish   50       NaN
4     Elina   35   50000.0
5     Fapul   47   20000.0
6    Ganesh   55  120000.0
7      Hari   53  100000.0
8       Itu   60  140000.0
9     Jyoti   79  150000.0

In [50]:
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
df

/tmp/ipykernel_6187/33204281.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)

       Name  Age         Salary
0      Ajay   25   23000.000000
1     Bijay   30   24000.000000
2   Chandan   20   80000.000000
3  Debasish   50   78555.555556
4     Elina   35   50000.000000
5     Fapul   47   20000.000000
6    Ganesh   55  120000.000000
7      Hari   53  100000.000000
8       Itu   60  140000.000000
9     Jyoti   79  150000.000000

In [51]:
df.drop_duplicates(inplace=True)
df

       Name  Age         Salary
0      Ajay   25   23000.000000
1     Bijay   30   24000.000000
2   Chandan   20   80000.000000
3  Debasish   50   78555.555556
4     Elina   35   50000.000000
5     Fapul   47   20000.000000
6    Ganesh   55  120000.000000
7      Hari   53  100000.000000
8       Itu   60  140000.000000
9     Jyoti   79  150000.000000